server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1145141919810
    url: jdbc:mysql://localhost:3306/super_mall?encoding=true&charset=utf8mb4